[package]
name = "erc-20-toy-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
rand = "0.8"
secp256k1 = { version = "0.29", features = ["rand-std"] } 
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
